### ISSUE TITLE
Not compile with Gradle plugin 1.5.20 because motion sensor

### ISSUE THREAD

**Issue by dariocavada** [zesage/panorama#52]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':motion_sensors' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by dariocavada** [comment]
I solve this putting a dependency_overrides in the `pubspec.yaml` file:

``` yaml
dependency_overrides:
 motion_sensors:
    git:
      url: https://github.com/zesage/motion_sensors
      ref: master
```
